### ISSUE TITLE
Troubles while build stage

### ISSUE THREAD

**Issue by nergal** [KuznetsovArtem/aha#1]
There problem while `gulp build` execution. Im getting following exception:

```
[15:41:12] Using gulpfile /media/nergal/Develop/sources/hotwire/workshop/aha/gulpfile.js
[15:41:12] Starting 'clean:dist'...
[15:41:12] Finished 'clean:dist' after 5.71 ms
[15:41:12] Starting 'build'...
[15:41:12] Starting 'images'...
[15:41:12] Starting 'copy:extras'...
[15:41:12] Starting 'copy:fonts'...
[15:41:12] Starting 'html'...
[15:41:12] Starting 'styles'...
[15:41:12] Finished 'build' after 353 ms
[15:41:12] Finished 'copy:fonts' after 19 ms
[15:41:12] Finished 'copy:extras' after 27 ms
[15:41:12] Finished 'styles' after 100 ms
[15:41:12] Finished 'images' after 446 ms
[15:41:12] Finished 'html' after 103 ms
[15:41:12] Starting 'client:build'...
[15:41:12] 'client:build' errored after 370 ms
[15:41:12] TypeError: undefined is not a function
    at Gulp.<anonymous> (/media/nergal/Develop/sources/hotwire/workshop/aha/gulpfile.js:190:20)
    at module.exports (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/index.js:214:10)
    at /media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/index.js:279:18
    at finish (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/lib/runTask.js:21:8)
    at /media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:129:20)
    at /media/nergal/Develop/sources/hotwire/workshop/aha/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
[15:41:12] Error in plugin 'run-sequence'
Message:
    An error occured in task 'client:build'.
```

Seems like gulp-useref package is broken.

**Comment by KuznetsovArtem** [comment]
Actually I didn't try to build the app. 'Gulp serve' might be enough for now.
